# Generated by Django 3.2.16 on 2023-02-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_auto_20230228_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
