# Generated by Django 3.2.16 on 2023-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_alter_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
