# Generated by Django 3.2.16 on 2023-03-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_address_zip_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
