# Generated by Django 3.2.16 on 2023-03-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0008_alter_address_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip_code2',
        ),
    ]
