# Generated by Django 3.2.16 on 2023-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0010_alter_address_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
