# Generated by Django 3.2.16 on 2023-03-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_alter_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='set_default_address',
        ),
    ]
