# Generated by Django 3.2.16 on 2023-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0012_rename_default_address_set_default_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='set_default_address',
            new_name='save_as_default_billing',
        ),
        migrations.AddField(
            model_name='address',
            name='save_as_default_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
