# Generated by Django 3.2.16 on 2023-03-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0013_auto_20230301_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='save_as_default_billing',
            new_name='set_default_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='save_as_default_shipping',
        ),
    ]
